docs/Pyrobot-class-diagram-func.md, docs/Pyrobot-class-diagram.md
There are two kind of pyrobot class diagram.
One of them contain functions and objects, the other just for class.
=> add pyrobot class diagram

myname.txt, tests/test_lec8_classes.py
change the name of the function to specificed form
=> Update lec 8 code

tests/test_lec9_inheritance.py
=> group13 update test_lec9_inheritance.py

tests/test_lec9_inheritance.py
Reverts ARG-NCTU/oop-python-nycu#75
=> Revert "group13 update test_lec9_inheritance.py"

tests/test_lec9_inheritance.py
Reverts ARG-NCTU/oop-python-nycu#84
Accidentally merge please follow the previous comment.
=> Revert "team15 lec9"

tests/test_lec9_inheritance.py
=> lec9 testcode group6

tests/team_17/add_path.py, tests/team_17/test_food.py
Add test_food.py and add_path.py in team_17
=> Add new folder team_17 in tests

tests/team_17/add_path.py, tests/team_17/test_food.py, tests/test_lec6_recursion_dictionaries.py
=> Add folder team_17 with test_food.py

tests/team1/add_path.py, tests/team1/pytest.ini, tests/team1/test_food.py, tests/team1/test_greedy.py, tests/team1/test_max_value.py, tests/team1/test_menu.py
=> team1_test_greedy.py

tests/team_12/add_path.py, tests/team_12/test_food.py
=> team12 testing code

tests/team_5/add_path.py, tests/team_5/test_food_5.py
group 5 test_food_5 @leowang707  @WuChangJin94
=> group 5 test_food_5

tests/team_8/add_path.py, tests/team_8/menu.py, tests/team_8/test_food.py, tests/team_8/test_greedy.py, tests/team_8/test_max_value.py, tests/team_8/test_menu.py
=> group 8 foodtest

tests/team_17/test_menu.py
=> Add tests to test_menu.py

tests/team_17/test_greedy.py
=> add tests to test_greedy.py

tests/team_15/add_path.py, tests/team_15/test_food.py
=> test: add foodtest

tests/team_6/add_path.py, tests/team_6/test_food.py, tests/team_6/test_menu.py
=> group06_tests

tests/team_7/add_path.py, tests/team_7/test_food.py, tests/test_lec8_classes.py
=> change directory name from "team7" to "team_7"

tests/team_5/60002-lecture3.py, tests/team_5/lecture3_graph.py, tests/team_5/test_city_planner.py, tests/team_5/test_digraph.py
=> add files for lec 3

tests/team_03/lec5_module.py, tests/team_03/plot_matplotlib.py, tests/team_03/test_drunk.py, tests/team_03/test_field.py, tests/team_03/test_location.py, tests/team_03/test_walk.py
=> add lec 5 file, pylab to plt

tests/team_7/lec8/download_data.sh, tests/team_7/lec8/lec8_module.py, tests/team_7/lec8/plot_hist.py, tests/team_7/lec8/test_lec8.py
=> add lec8 file

tests/group2/Lecture11/add_path.py, tests/group2/Lecture11/lec11_complexity_part2.py, tests/group2/Lecture11/test_lec11_complexity_part2.py, tests/group2/Lecture12/110612025_test_bubble_sort.py, tests/group2/Lecture12/110612025_test_merge_sort.py, tests/group2/Lecture12/add_path.py, tests/group2/Lecture12/lec12_sorting.py, tests/group2/Lecture12/test_lec12_bubble_buggy.py, tests/group2/Lecture12/test_lec12_bubble_sort.py, tests/group2/Lecture12/test_lec12_sorting.py, tests/group2/add_path.py
=> Add test code

tests/group5/test_lec12_couting_sort_112550174.py
Added the import statement for pytest in the counting sort test file. This change ensures that pytest functionalities can be used within the test file.
=> feat(tests): add pytest import to counting sort test

tests/group5/lec11/lec11_pytest_112550182.py, tests/group5/lec8/lec8_pytest_112550182.py, tests/group5/lec9/lec9_pytest_112550002.py, tests/group5/lec9/lec9_pytest_112550182.py, tests/group5/lec9/lec9_source_code.py
practice for class inheritance
@zhuchi76 麻煩助教了
=> 112550002 for lec9 class 繼承 sample code

pofeng.txt
=> Remove my name.txt file.

tests/group1/github_account_group1.txt, tests/group1/lec_8_testing_code_111514025.py
=> 3月17日的pull requests

tests/group4/113511103/test_lec9_inheritance.py
group4: lec9_inheritance.py 測試完成
- Animal、Dog、Cat 類別的基本行為測試
- 測試 speak() 方法是否正確 override
=> group4: 測試 lec9_inheritance 中 Animal/Dog/Cat 類別

tests/group1/lec_2_testing_code_111514013.py
lecture2_testing_code_111514013
=> lecture2_testing_code_111514013

tests/group4/113511103/test_lec6_part1_recursion.py, tests/group4/113511103/test_lec6_part2_recursion.py
本 PR 分為兩個檔案、共 10 次 commit：
- Part 1：fib, is_palindrome（含基礎與邊界測試）
- Part 2：lyrics_to_frequencies, towers（含邊界與順序驗證）
每段程式皆有標註所屬 commit，方便老師 trace 測試歷程。
=> group4: Lec6 第二版測試（10 commit，2 檔案）

tests/group4/113511103/test_lec9_inheritance_#2.py
- 以 10 次 commit 逐步開發與測試 lec9 中各類別行為：
- Animal：基本屬性與 __str__
- Cat：覆寫 speak 與 __str__
- Person：新增朋友、年齡差、speak
- Student：繼承 Person 並新增 major
- 測試涵蓋初始化、屬性存取、覆寫方法、邊界與繼承邏輯
=> group4: 測試 lec9 類別繼承（Animal, Cat, Person, Student）

tests/group4/113511103/test_lec6_recursion_dictionaries.py
- 共 5 次 commit，分別測試 lec6 中的四個主題：
- fib(x): 遞迴費氏數列
- is_palindrome(s): 回文判斷 + 字元清理
- lyrics_to_frequencies: 字頻統計
- towers(n): 河內塔步驟紀錄
- 額外加入進階與邊界測試，保證覆蓋完整案例
=> group4: 測試 lec6 遞迴與 dictionary 操作（fib, palindrome, lyrics, hanoi）

tests/group4/113511103/test_lec5_tuples_lists.py
- 重構 lec5 中的 quotient_and_remainder 與 get_data 為純函式
- 撰寫 pytest 測試覆蓋多組 tuple 結構與邊界輸入
=> group4: 測試 lec5 中 tuple 資料結構與資訊萃取

tests/group4/113511103/test_lec4_functions.py
- 測試 is_even_with_return, get_divisors, get_multiplication_table, find_common_factors
- 針對質數、最大公因數、乘法邏輯等進行多組 assert 驗證
=> group4: 測試 lec4 函式操作與共通因數

tests/group4/113511103/test_lec7_debug_except.py
測試 lec7_debug_except 中的 avg, primes_list, rev_list 等函式
=> group4: 測試 lec7_debug_except 中的 avg, primes_list, rev_list 等函式

tests/group4/113511103/test_lec10_file_processing.py, tests/group4/113511103/test_lec8_exception_scope.py
group4: 測試 lec8（例外處理）與 lec10（文字處理）
- lec8: 測試 divide, safe_int_conversion
- lec10: 測試 count_lines, extract_words, word_count
=> group4: 測試 lec8（例外處理）與 lec10（文字處理）

tests/group4/113511103/test_lec11_class_inheritance.py
=> group4: 測試 lec11 類別繼承與覆寫 speak 方法

tests/group4/113511103/test_lec12_sorting.py
- 加入自定義 bubble sort 排序測試
- 覆蓋空列表、單元素、重複、負數、浮點、混合型與隨機樣本等多種輸入情境
=> group4: 測試 lec12 排序（bubble sort 多場景測試）

tests/group4/113511103/test_lec3_strings_algos.py
- 測試 reverse_string, is_palindrome, char_frequency, is_prime, primes_below
- 含多組 assert 覆蓋空字串、特殊字元、質數判定與常見錯誤邊界
=> group4: 測試 lec3 字串處理與基本演算法

tests/group4/113511103/BouncyBall.py, tests/group4/113511103/FlappyBird.py, tests/group4/113511103/Laser_Dodge.py
This pull request adds a complete implementation of a Flappy Bird style game using Pygame.
📂 File path:
`group/113511103/flappy_bird.py`
🎮 Features:
- Basic Flappy Bird mechanics: gravity, jump, collision detection
- Random pipe generation with gap
- Score system based on pipes passed
- Game over screen on collision or out of bounds
✅ Code has been tested and runs smoothly on standard Python 3 + Pygame setup.
=> Add Flappy Bird Game Implementation in group/113511103

tests/group4/111651070/lec4_test.py
This pull request adds several new functions and corresponding test cases to the `lec4_test.py` file, expanding its functionality and test coverage. The changes include utility functions for cube root approximation, examples of function behavior, and tests for variable scope and function calls.
* Added `bisection_cuberoot_approx` and `bisection_cuberoot_approx_test` to compute and test cube root approximations using the bisection method. (`[tests/group4/111651070/lec4_test.pyR21-R85](diffhunk://#diff-539684975bea3dfb7998440a7363f1221a73a58afc9cb40b9c7050567c4e18e9R21-R85)`)
* Added several utility functions (`func_a`, `func_b`, `func_c`, `ff`, `f`, `g`, `h`, `i`, `j`, `k`) to demonstrate different programming concepts such as nested functions, variable scope, and function calls. …
=> Add Lec4 OCW Code Test

tests/group17/test_lec8_2.py, tests/group17/test_lec8_3.py, tests/group17/test_lec9.py, tests/group17/test_lec9_1.py, tests/group17/test_lec9_2.py, tests/group17/test_lec9_3.py, tests/group17/test_lec9_4.py, tests/group17/test_lec9_5.py
Added a new test file `test_lec8_2.py` under `tests/group17` to test the Fraction class. The tests include addition, subtraction, inversion, and error handling for invalid inputs. These tests ensure the correctness of the Fraction class implementation.
=> feat(tests): add unit tests for Fraction class

tests/group1/test_lec_4_testing_code_111514013.py
=> lec_4_testing_code_111514013

tests/group10/test_lec4_116.py
* Updated the import statement in `test_lec4_116.py` to reflect the correct module path.
* Ensures compatibility with the current project structure.
=> fix(tests): 🐛 correct import path for `lec4_module`

tests/group4/111651070/lec10_test.py, tests/group4/111651070/lec11_test.py, tests/group4/111651070/lec12_test.py, tests/group4/111651070/lec8_test.py, tests/group4/111651070/lec9_test.py
This pull request introduces multiple changes across several test files, focusing on adding new functionality, improving test coverage, and enhancing code clarity. The most significant updates include the addition of search-related functions and tests, restoration and enhancement of `Fraction` and `intSet` classes, and the introduction of several inheritance-based classes with accompanying tests.
* [`tests/group4/111651070/lec10_test.py`](diffhunk://#diff-3def65ed8c6b6d381c36fec66e20a9ed62e1ea5a7133a003e270316fb32e2f97R1-R87): Added functions `linear_search`, `search`, `isSubset`, and `intersect`, along with their corresponding test cases to validate their functionality.
* [`tests/group4/111651070/lec8_test.py`](diffhunk://#diff-39fb9d77cbe6e65c1eece5d84ce174c9369a60fe68c1d6b9b2173874bbb51 …
=> Add Lec6, 8, 9, 10, 11, 12 OCW Code Test

tests/group1/test_lec_5_drunk_111514013.py, tests/group1/test_lec_5_field_111514013.py, tests/group1/test_lec_5_location_111514013.py, tests/group1/test_lec_5_walk_111514013.py
=> lecture5_testing_code

tests/group8/group_tree/lec7/Makefile, tests/group8/group_tree/lec7/lec7.py, tests/group8/group_tree/lec7/test_lec7.py, tests/group8/group_tree/lec8_class/Makefile, tests/group8/group_tree/lec8_class/lec8.py, tests/group8/group_tree/lec8_class/test_lec8.py
Changes to be committed:
new file:   Makefile
new file:   lec8.py
new file:   test_lec8.py
=> lec testcode

tests/group1/test_lec_8_sample_111514013/download_data.sh, tests/group1/test_lec_8_sample_111514013/test_lec_8_sample_testing_code_111514013.py
lec8_sample_testing_code_111514013
=> lec8_sample_testing_code_111514013

tests/group6/else/LeetCodePractice/Evaluate Boolean Binary Tree.py, tests/group6/else/LeetCodePractice/Fibonacci Number.py, tests/group6/else/LeetCodePractice/Find if Path Exists in Graph.py, tests/group6/else/LeetCodePractice/Find the Value of the Partition.py, tests/group6/else/LeetCodePractice/Jump Game III.py, tests/group6/else/LeetCodePractice/Minimize the Maximum Difference of Pairs.py, tests/group6/else/LeetCodePractice/Minimum Score of a Path Between Two Cities.py, tests/group6/else/LeetCodePractice/Minimum Time to Complete Trips.py, tests/group6/else/LeetCodePractice/Number of Enclaves.py, tests/group6/else/LeetCodePractice/Number of Provinces.py, tests/group6/else/LeetCodePractice/Remove Nodes From Linked List.py, tests/group6/else/LeetCodePractice/Roman to Integer.py, tests/group6/else/LeetCodePractice/Sort the People.py, tests/group6/else/LeetCodePractice/TwoSum, tests/group6/lec_test_codes/test_lec5_module.py, tests/group6/lec_test_codes/test_lec7_debug_except.py, tests/group6/lec_test_codes/test_lec8_classes.py, tests/group6/lec_test_codes/test_lec9_inheritance.py, tests/group6/lec_test_codes/test_menu.py
* Implemented `test_fast_max_val_empty` to verify that `fast_max_val` returns a total value of 0 when no foods are provided.
=> test: ✨ add test for empty fast_max_val case

tests/group4/113101013/test_basic.py, tests/group4/113101013/test_lec10.py, tests/group4/113101013/test_lec11.py, tests/group4/113101013/test_lec12_sorting.py, tests/group4/113101013/test_lec3_strings.py, tests/group4/113101013/test_lec4_function.py, tests/group4/113101013/test_lec5.py, tests/group4/113101013/test_lec6.py, tests/group4/113101013/test_lec7.py, tests/group4/113101013/test_lec8.py, tests/group4/113101013/test_lec9.py
=> add test for several lec

tests/group4/113101013/test_lec3_strings.py, tests/group4/113101013/test_lec6.py, tests/group4/113101013/test_lec7.py
* Added basic, edge, punctuation, and unicode tests for the `is_palindrome` function to ensure robustness and accuracy.
=> feat(tests): ✨ add comprehensive tests for `is_palindrome`
